### ISSUE TITLE
Quackle on MacOS Ventura 13.6.7 board completely white, missing colored premium squares

### ISSUE THREAD

**Issue by teslum** [quackle/quackle#132]
I just downloaded Quackle from https://people.csail.mit.edu/jasonkb/quackle/ on my Mac running MacOS Ventura 13.6.7 (22G720). The Scrabble board is all white with no designation of where the colored premium squares are ("triple letter score", "double word score", etc.). Screenshot attached. How do I fix this?

<img width="838" alt="image" src="https://github.com/quackle/quackle/assets/73007292/76a02513-9280-4f09-8376-5d635ab2c8b9">

**Comment by teslum** [comment]
Didn't know that this "configure the board yourself" thing was a way to avoid getting around copyright issues.

**Comment by jfultz** [comment]
Quackle is just a crossword games program.  It does contain some copyrighted dictionaries that we believe we have the rights to redistribute (and we credit those copyrights appropriately).  We try to otherwise actively avoid copyright or trademark infringement upon the many crossword games that are out there.  One set of copyright claims is on the design of the game board.
