### ISSUE TITLE
allow multi-core computer simulation

### ISSUE THREAD

**Issue by domino14** [quackle/quackle#3]

**Comment by jfultz** [comment]
I'm thinking of implementing this as an abstract base class which the process is responsible for providing an implementation for.  Think Abstract Factory Pattern.  Then we could use QThreadPool from the interface.  Or implement pthreads for command-line implementations that don't have Qt dependencies.

So, sim.cpp merely defines and uses the interface...not the implementation.

**Comment by domino14** [comment]
I had some code here that actually did multicore sim, but not much else...  https://github.com/domino14/quackle/tree/improvement/3/multicore if this helps :)

I like that idea, although it seems like more work. Would pthread not work on Windows at all?

**Comment by jfultz** [comment]
Come to think of it, I should have said std::thread rather than pthreads.  I've already begun broaching just a tiny bit of C++11 as of the 1.0 release.  Enough to slightly break builds, but not so much that it couldn't be undone.  If nobody complains, I'll probably dive deep with C++11 in the near future.  It means leaving some compilers behind.  But C++11 is a four year old standard.

That having been said, the threading is not, I think, the hard part.  Sims can be completely independent of one another, and pretty much only share read-only resources.  It's possible no locking will be needed at all to perform a sim.  The hard part is that this works out to a map-reduce type of problem, and so we basically need a multi-producer-single-consumer queue.  I hadn't thought about this much before, but in a bit of googling, it looks like my assumption that such objects might be a part of thread pool implementations is broken, but on the other hand, there are a number of portable MPMC implementations out there, including lockfree ones.  That's nice.

So, maybe instead, I can do just a single implementation and have it be sensibly portable.

When I get a chance to start working on this, I'll take a look at your implementation.

**Comment by domino14** [comment]
I'm not a Quackle maintainer but I'm totally in favor of C++11 :) :+1:

I think in practice the problem can be reasonably simple. All you need is a way for the threads to communicate back to the GUI or main thread. You can probably make it send a signal every 10 iterations or so. Computing the stdev/mean will be a little tricky because you need to sum them all up correctly.

**Comment by jfultz** [comment]
Computing the standard deviation/mean parallelized sim data is the quintessential map-reduce problem.  Buffered channels in Go are fixed-size MPMC queues.  You are saying the same thing I'm saying.

**Comment by jfultz** [comment]
Just merged the `multithread_sim` branch to master after a fair amount of testing on Mac and Windows (haven't tested Linux, but it's all common code, so it should work fine).  Resolved in commit 5a746a6b1066a.
