### ISSUE TITLE
Lexicon can't be built from large word lists

### ISSUE THREAD

**Issue by alkamid** [quackle/quackle#44]
If a word list is too large, the "Build lexicon database..." option in the GUI seems to fail. To reproduce this, download the list from http://sjp.pl/slownik/growy/, open Quackle, go to Settings -> Lexicon -> Add new lexicon -> (choose Polish alphabet) -> Add words from file... This should go smoothly and you should have a new lexicon in the list. However, if you then click on "Build lexicon database", after a few seconds you get the following message:

`Your lexicon is too large to be represented using the internal database format. Operation aborted.`

Maybe building a GADDAG from a long list is pointless, I'm not sure, but I'm letting you know about this anyway.

Bonus question: when I "Add new lexicon", where is it stored? I can play with it in Quackle, but I can't find the .dawg file. (I'm on linux)

**Comment by jfultz** [comment]
Yeah, this is intentional.  Two issues...first, building the GADDAG of such a large list takes a prohibitively long time.  But that's the less serious issue.  The more serious one is that the GADDAG format literally cannot support that many words.  If you try to create one, it will, necessarily, create a GADDAG that has erroneous internal pointers, causing the resulting dictionary lookups to be inaccurate.

I thought about this a long time when I first introduced the GADDAG builder, tried it on the Polish dictionary, and discovered the problem.  I could have changed the GADDAG format, but that would have required some decent amount of work, and it wouldn't have fixed the first problem.  IIRC the GADDAG was taking multiple minutes to build on my systems, which are generally top of the line.

So, I decided instead to put a hard threshold into the GADDAG builder.   Here's a relevant snippet from `gaddagfactory.h`:

```
// This isn't a strict maximum...you can go higher...but too much higher, and you risk overflowing
// node pointers, which will get you garbage words.  The OSPS dictionary is known to trigger
// such overflows.
const int QUACKLE_MAX_GADDAG_WORDCOUNT = 500000;
```

Maybe someday we'll come up with a superior solution to GADDAG, at which point, we should revisit this.  But, for now, I have no intention of changing this behavior.

**Comment by jfultz** [comment]
I missed your second question.  All user data is stored in a subdirectory of the directory returned by this call:

```
QDesktopServices::storageLocation(QDesktopServices::DataLocation)
```

That generally is going to translate to:
Mac: `~/Library/Application Support/Quackle.org/Quackle`
Windows: `\Users\<username>\AppData\Local\Quackle.org\Quackle`

Sorry, don't remember Linux.  And the Windows version might be different, depending upon the version of Windows you're running.

**Comment by jfultz** [comment]
Googling suggests it might be `~/.local/share/data/Quackle.org/Quackle` under Linux.
