### ISSUE TITLE
Add a C api

### ISSUE THREAD

**Issue by martindemello** [quackle/quackle#80]
A C api would let us write other langauge bindings, and essentially form a scripting interface for quackle. Issues that that would go a long way to closing include #47, #46, and #27 

(There are a tiny handful of languages that can interface with C++ but it seems like a C layer would add greater utility)

**Comment by jfultz** [comment]
I'm not opposed to this, but it's not my strategy for implementing those issues (and also #45).  I'm focusing on command-line utilities...which won't provide programmatic interfaces, but *will* be conveniently scriptable.  I already have the (still fairly early) beginnings of code to do this, but nothing pushed to Github, yet.

So, I have no intention to take up this issue in the foreseeable future.  If somebody else were to work on a C API, I would seriously consider such a PR so long as it's nothing more than a lightweight layer riding on top of the current C++ implementation.

Since this isn't in the list of projects that I want to work on, I'm not going to assign it to a developer or project.

**Comment by martindemello** [comment]
i'm considering working on it, i filed the bug to see if anyone else was interested too. the c interface will be pretty lightweight, mostly the standard technique of having functions that take a pointer to  class and call a method on it.

**Comment by jfultz** [comment]
Incidentally, @martindemello, you might want to take a look at #35 which was merged some time ago.  I don't know anything about SWIG, and I haven't tested its application for Quackle, but the claim was that it would support bindings like this for at least some languages.

**Comment by martindemello** [comment]
oh nice, if someone has already done swig bindings that should make this a bunch easier. i held back from that because i wasn't sure how to make swig play well with qt.

**Comment by martindemello** [comment]
(also i agree with @gokceneraslan's comment about removing qt from quackleio; i'd be willing to put some work into that if you think it's a good idea)

**Comment by jfultz** [comment]
I'm happy to see it done (if it's done well), but I'm not sure if you appreciate the pain in the butt doing that would be.

There's some low-hanging fruit to be sure (like `QRegExp` in dictimplementation.cpp), but a lot of it requires a significant amount of rearchitecture to consider how it would work minus Qt, and the result impacts not only quacker, but also some of the existing command-line programs (...which I hope to eventually obsolete...).

**Comment by martindemello** [comment]
yeah, i agree, and integrating the result with quacker would be a huge pain and possibly make it not worth it. i'll take a look and see but i'm not too optimistic either. still sounds like a thing that would be good to have.

**Comment by martindemello** [comment]
the swig bindings seem to be doing a good job, closing this.
