### ISSUE TITLE
Blurred board/large tiles

### ISSUE THREAD

**Issue by Vinceinhoc** [quackle/quackle#87]
Yesterday I downloaded Quackle 1.0.4 and I encountered some problems with graphics - it seems that board is a bit blurred and tiles are huge comparing to the previous version. I didn`t find any way to fix this - can someone help me with it? :)

![67219371_493770028098862_4229634538415849472_n](https://user-images.githubusercontent.com/53296673/61862459-38be4380-aece-11e9-9ab0-7d1366bcfa7b.png)

**Comment by jfultz** [comment]
The previous version didn't support high-res displays and (because of Qt's default behavior) did the stupidest thing possible...on, say, a 200%-scaled display, it reacted by making things twice as small.  So, the change in the sizes of things is intentional and correct.

But the text on the board and tiles should be high-res, not pixelated.  That's a legit issue.

Incidentally, one of the issues I discovered when moving to the new version on a high-res display is depicted here...you get a *really* wide history view on the left.  You can resize that.  Move the mouse between the history view and the game board, and it will turn into a splitter resize cursor, that you can use to make the history view a bit smaller.
